name: Publish Site

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - run: chmod +x ./gradlew
      - name: Build the assembler and create the site
        uses: gradle/gradle-build-action@v2
        with:
            arguments: build assembleSite
        
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.8
        with:
          path: ./web_output
        
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v2.0.2
